export const theme = {
  colors: {
    primary: '#ED1C24',
    primaryDark: '#C0151B',
    primaryLight: '#FDECEA',
    background: '#F7F7F7',
    surface: '#FFFFFF',
    border: '#EBEBEB',
    textPrimary: '#1A1A1A',
    textSecondary: '#6B6B6B',
    textMuted: '#ABABAB',
    success: '#2E7D32',
    successLight: '#E8F5E9',
    warning: '#E65100',
    warningLight: '#FFF3E0',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  font: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
};
